[workspace]
members = [
  ".",
  "ferrum_compiler",
  "ferrum_macros",
  "ferrum_netlist"
]

[package]
name = "ferrum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [package.metadata.rust-analyzer]
# rustc_private = true

[[example]]
name = "blinking"
crate-type = ["staticlib"]

[dependencies]
derive-where = "1.2.2"
ferrum_macros = { path = "ferrum_macros" }
ferrum_netlist = { path = "ferrum_netlist" }
strum = { version = "0.25.0", features = ["derive"] }
