[package]
name = "fhdl_netlist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_enums = "0.8.2"
bumpalo = { version = "3.13.0", features = ["collections"] }
derive-where = "1.2.5"
either = "1.9.0"
indexmap = "2.0.0"
fnv = "1.0.7"
smallvec = "1.11.0"

