[package]
name = "fhdl_netlist"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
auto_enums = "0.8.2"
bumpalo = { version = "3.13.0", features = ["collections"] }
derive-where = "1.2.5"
either = "1.9.0"
fhdl_blackbox = { path = "../fhdl_blackbox/" }
fhdl_const_func = { path = "../fhdl_const_func/" }
once_cell = "1.18.0"
smallvec = "1.8.1"

