[package]
name = "fhdl_blackbox"
version = "0.1.0"
edition = "2021"

[features]
encoding = []

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
strum = { version = "0.25.0", features = ["derive"] }
