[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferrum_hdl = { git = "https://github.com/zshell31/ferrum_hdl.git", branch = "mir", version = "0.2.0" }
