[package]
name = "fhdl_compiler"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
anstream = "0.6.4"
anstyle = "1.0.4"
bumpalo = { version = "3.14.0", features = ["collections", "allocator_api"] }
cargo_toml = "0.19.0"
either = "1.9.0"
ferrum_hdl = { path = "../" }
fhdl_blackbox = { path = "../fhdl_blackbox" }
fhdl_netlist = { path = "../fhdl_netlist" }
if_chain = "1.0.2"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.11.0"
thiserror = "1.0"
petgraph = "0.6.4"
