[package]
name = "ferrum_netlist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_enums = "0.8.2"
indexmap = "2.0.0"
ferrum = { path = "../" }
fnv = "1.0.7"

