[package]
name = "ferrum_netlist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_enums = "0.8.2"
either = "1.9.0"
ferrum = { path = "../" }

